### ISSUE TITLE
alexey's branch updates

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#65]
I've finally managed to make HistoneDB run from scratch on my laptop.
1) I had to rewrite the buildvariants.py - so it is not dependent on the NR. otherwise it took forever to start the database up and test it. So the curated are now loaded first.
2) I simplified some things along the way. - no unclassified variants any more. unknowns are still there, but we should also delete them after population of DB.
3) Fixed the STATIC_ROOT issue in settings.py - all our routines use now STATIC_ROOT_AUX . STATIC_ROOT - commented out, otherwise it breaks some modules in django.
4) core_type - is confusing (H1 is not core, all others are) - refactored to hist_type
5) migrations in djangophylocore - deleted - they break setup
6) integrated the seed seq without gis, they have to have NOGI_number id
7) seed seqs get tax id directly from NCBI
8) Simplified the constructions of query sets in  search.py HistoneSearch, since there are no unknowns and unclassified, no need to see if there is a used_for_classification field.
9) refactored the urls.py to be compatible with django 1.8 and further.

**Comment by edraizen** [comment]
1) Sounds great, thanks!

2) a. I'm not sure why you would want to this. Maybe the name "unclassifiedH2A" is not informative, but it is what I refered to the sequences that did not score well against any variant HMM, but scored well against the full core HMM defined from sequences the previous histone database. It means "It is likely this core histone, but we don't the variant yet"
   b. Removing Unknowns should be fine - but it might be helpful if people are analyzing there sequences, and it come up as unknown, instead of showing no results.

3) Great, that will fix a lot of things

4) good point

5) thanks

6) Great idea, what is the identifier now? What happens when it comes up and someone wants to view it entrez?

7) I thought they all had them? And if you just use the name in djangophylcore you get the full taxonomy id. Not sure what you are doing here

8) I'll look what you did, but I made used_for_classification to specify which score we used for classification so we didn't have to redo that algorithm over again. Say H2A.B score was greater than H2A.L, but the score for H2A.B was below the threshold for H2A.B, but the score for H2A.L was above the threshold. The used_for_classification boolean lets us know which to choose to display, how did you get around this?

9) Sounds good

**Comment by edraizen** [comment]
Ok, I've merged merged our branches and was able to get everything running. We still have the problem where there are sequences that have no score with Score.used_for_classification set True, which is messing up searches and building the sunbursts. This is what I am working on right now.

**Comment by molsim** [comment]
Cool!
have you pushed it to alexey_merged?
I still get "Exception Value:	
unindent does not match any outer indentation level (search.py, line 264"

**Comment by edraizen** [comment]
We successfully merged them, so I am closing this now
